name: "💡 Nowy temat / pytanie"
description: Opisz, co chcesz zbudować, o co zapytać, albo co rozwinąć
title: "[Temat] Krótki opis"
labels: [pomysł, pytanie]
body:
  - type: textarea
    id: opis
    attributes:
      label: Co chcesz osiągnąć?
      description: Napisz, co Ci chodzi po głowie lub co chcesz zbudować.
      placeholder: np. "Jak stworzyć własny init w Alpine?"
    validations:
      required: true
  - type: textarea
    id: kontekst
    attributes:
      label: Kontekst lub co już zrobiłeś
      description: Co już działa, a co nie? Dodaj kod, logi lub pomysły.
